version: '3.8'
services:
  comfyui:
    image: ghcr.io/ai-dock/comfyui:latest-cuda
    ports:
      - "1111:1111"
      - "8188:8188"
    volumes:
      - ./models:/opt/ComfyUI/models
      - ./input:/opt/ComfyUI/input
      - ./output:/opt/ComfyUI/output
    environment:
        - NVIDIA_VISIBLE_DEVICES=all
        - NVIDIA_DRIVER_CAPABILITIES=all
        - WEB_AUTHENTICATION=false
        - WEB_USER=user
        - WEB_PASSWORD=password
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]