version: '3.8'
# services:
#   comfyui:
#     image: comfyui/comfyui
#     ports:
#       - "8188:8188"
#     volumes:
#       - ./models:/app/models
#       - ./input:/app/input
#       - ./output:/app/output
#     deploy:
#       resources:
#         reservations:
#           devices:
#             - driver: nvidia
#               count: 1
#               capabilities: [gpu]
services:
  comfyui:
    image: ghcr.io/ai-dock/comfyui:latest-cuda
    runtime: nvidia
    ports:
      - "1111:1111"
      - "8188:8188"
    volumes:
      - ./models:/opt/ComfyUI/models
      - ./input:/opt/ComfyUI/input
      - ./output:/opt/ComfyUI/output
    environment:
        - NVIDIA_VISIBLE_DEVICES=all
        - WEB_AUTHENTICATION=false
        - WEB_USER=user
        - WEB_PASSWORD=password